change workflow and terraform files

diff --git a/.github/workflows/nodejs-ci.yml b/.github/workflows/nodejs-ci.yml
--- a/.github/workflows/nodejs-ci.yml
+++ b/.github/workflows/nodejs-ci.yml
@@ -24,8 +24,14 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
+      - name: Verify ACR Exists
+        run: |
+          echo "Checking ACR..."
+          az acr show -n $ACR_NAME -g $RG_NAME || (echo "ACR NOT FOUND!" && exit 1)
+
       - name: ACR Login
-        run: az acr login --name $ACR_NAME
+        run: |
+          az acr login --name $ACR_NAME
 
       - name: Docker Build & Push
         run: |
